# Generated by Django 2.1.5 on 2019-09-28 07:12

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('isAdmin', models.BooleanField(default=False)),
                ('createDate', models.DateTimeField()),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('userManage', django.db.models.manager.Manager()),
            ],
        ),
    ]
